openapi: 3.0.3
info:
  title: Binar News
  description: |-
    Aplikasi ini akan berguna untuk membantu students mendapatkan informasi terbaru tentang kelas yang ada di Binar Academy.
  contact:
    email: alex@mail.com
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
  - url: https://test.binarnews.com/api/v1
  - url: https://binarnews.com/api/v1
tags:
  - name: User
    description: Everything about your Users
paths:
  /users:
    post:
      tags:
        - User
      operationId: post-create-new-user
      summary: ini summary
      description: ini description
      requestBody:
        $ref: "#/components/requestBodies/CreateUser"
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/UserModel"
    get:
      tags:
        - User
      operationId: get-fetch-all-user
      summary: ini summary
      description: ini description
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: "page of content"
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: "limit content per page"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          pagination:
                            $ref: "#/components/schemas/Pagination"
                          users:
                            type: array
                            items:
                              $ref: "#/components/schemas/UserModel"
  "/users/{userId}":
    get:
      tags:
        - User
      operationId: get-fetch-user-detail
      summary: ini summary
      description: ini description
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: "userId wajib diisi"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/UserModel"
components:
  schemas:
    BasicResponse:
      title: BasicResponse
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: "success"
    UserModel:
      title: UserModel
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "bujang"
        email:
          type: string
          example: "bujang@mail.com"
    Pagination:
      title: Pagination
      type: object
      properties:
        links:
          type: object
          properties:
            next:
              type: string
              example: "https://domain.com/users?page=3&limit=10"
            prev:
              type: string
              example: "https://domain.com/users?page=1&limit=10"
        total_items:
          type: integer
          example: 100
  requestBodies:
    CreateUser:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                example: "bujang"
              email:
                type: string
                example: "bujang@mail.com"
