POST http://localhost:4000/api/v1/users
Content-Type: application/json

{
    "name":"joko",
    "email":"joko@mail.com"
}

###
GET http://localhost:4000/api/v1/users?limit=10&page=1

###
GET http://localhost:4000/api/v1/users/1


###
PUT http://localhost:4000/api/v1/users/2
Content-Type: application/json

{
    "name":"alex",
    "email":"alex@mail.com"
}


###
DELETE http://localhost:4000/api/v1/users/3

###
POST http://localhost:4000/api/v1/posts
Content-Type: application/json

{
    "title":"membuat api bank",
    "categories":[
        {
            "id":1,
            "name":"express"
        },
        {
            "id":2,
            "name":"api"
        },
        {
            "id":3,
            "name":"backend"
        }
        ],
    "authorId":1
}


###
GET http://localhost:4000/api/v1/posts/1