POST http://localhost:3000/notification
Content-Type: application/json

{
    "user_id":1,
    "title":"New message 2",
    "body":"pesan baru kedua"
}

###
GET http://localhost:3000/notification?user_id=1