POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name":"sabrina",
    "email":"sabrina@mail.com",
    "password":"sabrina123",
    "password_confirmation":"sabrina123"
}


###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"sabrina@mail.com",
    "password":"sabrina123"
}


###
GET http://localhost:3000/api/v1/auth/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjk3NjQxMjQ0fQ.o6P4D0d85BL7bex4hG-mzstfDTITTW1Cu6vTOgZU9oU
